# Generated by Django 5.2.7 on 2025-10-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_bio_student_email_public_student_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_public',
        ),
    ]
